name: bottom_navbar_player
description: A Flutter plugin to play media in BottomNavigationBar.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: efafi.mostafa.bottom_navbar_player
        pluginClass: BottomNavbarPlayerPlugin
      ios:
        pluginClass: BottomNavbarPlayerPlugin
      linux:
        pluginClass: BottomNavbarPlayerPlugin
      macos:
        pluginClass: BottomNavbarPlayerPlugin
      windows:
        pluginClass: BottomNavbarPlayerPluginCApi


