name: bottom_navbar_player
description: A Flutter plugin to play media in BottomNavigationBar and bottomSheet with `file`, `web` and `asset` playback capabilities.
version: 0.0.2
homepage: https://github.com/mostafa-efafi/bottom_navbar_player

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  just_audio: ^0.9.32

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: efafi.mostafa.bottom_navbar_player
        pluginClass: BottomNavbarPlayerPlugin
      ios:
        pluginClass: BottomNavbarPlayerPlugin
      linux:
        pluginClass: BottomNavbarPlayerPlugin
      macos:
        pluginClass: BottomNavbarPlayerPlugin
      windows:
        pluginClass: BottomNavbarPlayerPluginCApi


